# Generated by Django 4.1.2 on 2022-10-31 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_remove_configuracion_content_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Configuracion',
        ),
    ]
